export const stateModel =
{
    states:
    [
        {
            id:'myDevice',
            states:
            [
                {
                    id:'idle',
                    $type:'initial',
                    transitions:
                    [
                        {
                            event:'go',
                            target:'busy'
                        }
                    ]
                },
                {
                    id:'busy',
                    $type:'parallel',
                    onEntry:function(){port.setOpen(true);},
                    transitions:
                    [
                        {
                            event:'e',
                            target:'idle',
                        },
                        {
                            event:'c',
                            target:'s22'
                        }
                    ],
                    states:
                    [
                        {
                            id:'s1',
                            transitions:
                            [
                                {
                                    event:'c',
                                    target:'s12'
                                },
                                {
                                    event:'d',
                                    target:'s21'
                                }
                            ],
                            states:
                            [
                                {
                                    id:'s11',
                                    onEntry:(event)=>{console.log("w");},
                                    onExit:(event)=>{console.log("y");},
                                },
                                {
                                    id:'s12',
                                    onEntry:(event)=>{console.log("y");},
                                    onExit:(event)=>{console.log("z");},
                                    transitions:
                                    [
                                        {
                                            event:'g',
                                            target:'s11'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            id:'s2',
                            states:
                            [
                                {
                                    id:'s21',
                                    transitions:
                                    [
                                        {
                                            event:'f',
                                            target:'idle'
                                        }
                                    ]
                                },
                                {
                                    id:'s22',
                                    onEntry:(event)=>{/*this.send({name:'h',data:event});*/}
                                }
                            ],
                        },
                        {
                            id:'s3',
                            $type:'parallel',
                            transitions:
                            [
                                {
                                    event:'c',
                                    target:'s12'
                                }
                            ],
                            states:
                            [
                                {
                                    id:'s31',
                                    transitions:
                                    [
                                        {
                                            event:'h',
                                            target:'s31',
                                            onTransition:(event)=>{console.log('a');}
                                        }
                                    ]
                                },
                                {
                                    id:'s32',
                                    onEntry:(event)=>{port.listenTo();}
                                }
                            ]
                        }
                    ]
                }
            ],
            transitions:
            [
                {
                    event:'stop',
                    target:'$final'
                }
            ]
        },
        {
            id:'$final',
            onEntry:(event)=>{port.setOpen(false);}
        }
    ]
};